### ISSUE TITLE
Text of floating button out of button when scroll top

### ISSUE THREAD

**Issue by DavideM12** [ajomuch92/flutter-scrolling-fab-animated#1]
Hi,

when I scroll to top the package expands the floating button with the text and it's ok.
But for a while in the transition, the text is out from the button (when the text come from right to left) and when the transition is complete the text is correctly over the button.

I tested it with flutter 2.5.3

Thank you

**Comment by ajomuch92** [comment]
Thanks @DavideM12 for reporting this issue, let me check it

**Comment by ajomuch92** [comment]
New version uploaded, please try and let me know if it's ok. Thanks @DavideM12

**Comment by DavideM12** [comment]
I have again the same issue.

Tested with iPhone XS Max - iOS 15.1

**Comment by ajomuch92** [comment]
Hey @DavideM12 can you upload a gif or video showing the issue please?
