### ISSUE TITLE
onLongPress

### ISSUE THREAD

**Issue by 0xecute** [ajomuch92/flutter-scrolling-fab-animated#10]
Hi,
Thank you for this great package.
It would be nice to add the onLongPress feature.
In InkWell you have the "onLongPress" features that will allow this to be done easily.
What do you think ?
Thanks

**Comment by ajomuch92** [comment]
Hi @0xecute 
Thanks for your idea, sounds great, I will add it when I can

**Comment by ajomuch92** [comment]
A new version was release with this feature @0xecute
