### ISSUE TITLE
FAB Theme

### ISSUE THREAD

**Issue by luis901101** [ajomuch92/flutter-scrolling-fab-animated#4]
Fab default theme should be taken from context scheme color theme as the material FAB does. This means FAB background, text and icon colors.

**Comment by ajomuch92** [comment]
This bug was closed [here ](https://github.com/ajomuch92/flutter-scrolling-fab-animated/commit/4adc2b0727d48a56ecab4993627bc90d83d83ba7). Icon and text are passed as widget, you can control them, not neccesary an update for that
