### ISSUE TITLE
Scroll collapse/expand inverted

### ISSUE THREAD

**Issue by luis901101** [ajomuch92/flutter-scrolling-fab-animated#5]
Previous version showed fab expanded by default and after user scrolls down the button collapsed. Now it’s inverted, button shows up collapsed and after user scrolls down it gets expanded. This is not a proper behavior, when user scrolls down button should collapse in order to give more viewable space for the screen content. Maybe in some cases this inverted behavior could be the expected one, anyway this should be property of the button, something like `inverted: true|false` to let the dev to choose the behavior.

**Comment by ajomuch92** [comment]
Thanks for noticing this bad behavior. I will fix it and add a new version

**Comment by luis901101** [comment]
Good thanks

**Comment by ajomuch92** [comment]
A new version was release with your observations. Thanks for your help @luis901101
