### ISSUE TITLE
Remove debug print

### ISSUE THREAD

**Issue by SeriousMonk** [ajomuch92/flutter-scrolling-fab-animated#6]
Fabulous widget! 

This is not really an important issue, however I just wanted to put it out there. Currently this widget prints loads of debug prints (of the widget width I presume) while scrolling.
Removing them would reduce the noise in the console :). But again, it's not a big deal.

**Comment by ajomuch92** [comment]
Done, thanks for noticing this issue buddy. A new version was published with this fix.
